# ################################################################################################### #
#                                                                                                     #
#                            ████████╗███╗   ███╗       █████╗ ██████╗ ██╗                            #
#                            ╚══██╔══╝████╗ ████║      ██╔══██╗██╔══██╗██║                            #
#                               ██║   ██╔████╔██║█████╗███████║██████╔╝██║                            #
#                               ██║   ██║╚██╔╝██║╚════╝██╔══██║██╔═══╝ ██║                            #
#                               ██║   ██║ ╚═╝ ██║      ██║  ██║██║     ██║                            #
#                               ╚═╝   ╚═╝     ╚═╝      ╚═╝  ╚═╝╚═╝     ╚═╝                            #
#                                                                                                     #
#                                                                                                     #
#  This file is part of TM-API, a Spigot/BungeeCord API.                                              #
#                                                                                                     #
#  TM-API is free software: you can redistribute it and/or modify                                     #
#  it under the terms of the GNU General Public License as published by                               #
#  the Free Software Foundation, either version 3 of the License, or                                  #
#  (at your option) any later version.                                                                #
#                                                                                                     #
#  TM-API is distributed in the hope that it will be useful,                                          #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of                                     #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                      #
#  GNU General Public License for more details.                                                       #
#                                                                                                     #
#  You should have received a copy of the GNU General Public License                                  #
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.                             #
#                                                                                                     #
# ################################################################################################### #


# ##################################################################################### #
#                                 ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗                                 #
#                                 ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗                                 #
#                                 ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝                                 #
#                                                                                       #
updates:                                                                                #
# ##################################################################################### #

  # Turn to true for enable plugin updates checker (Available) :
  checker: true

  # Send message to admins (not available) :
  adminMsg:
    # Turn to true to enable update warning
    use: false
    # Message design
    prefix: "&f[&6UpdateChecker&f] "
    suffix: "&f&l->&f "
    message: "&6New update is available !"


# #################### API made by PataPom - Licensed under GPL3 License. #################### #