# ################################################################################################### #
#                                                                                                     #
#                            ████████╗███╗   ███╗       █████╗ ██████╗ ██╗                            #
#                            ╚══██╔══╝████╗ ████║      ██╔══██╗██╔══██╗██║                            #
#                               ██║   ██╔████╔██║█████╗███████║██████╔╝██║                            #
#                               ██║   ██║╚██╔╝██║╚════╝██╔══██║██╔═══╝ ██║                            #
#                               ██║   ██║ ╚═╝ ██║      ██║  ██║██║     ██║                            #
#                               ╚═╝   ╚═╝     ╚═╝      ╚═╝  ╚═╝╚═╝     ╚═╝                            #
#                                                                                                     #
#                                                                                                     #
#  This file is part of TM-API, a Spigot/BungeeCord API.                                              #
#                                                                                                     #
#  TM-API is free software: you can redistribute it and/or modify                                     #
#  it under the terms of the GNU General Public License as published by                               #
#  the Free Software Foundation, either version 3 of the License, or                                  #
#  (at your option) any later version.                                                                #
#                                                                                                     #
#  TM-API is distributed in the hope that it will be useful,                                          #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of                                     #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                      #
#  GNU General Public License for more details.                                                       #
#                                                                                                     #
#  You should have received a copy of the GNU General Public License                                  #
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.                             #
#                                                                                                     #
# ################################################################################################### #

# ##################################################################################### #
#                                    ╔╦╗╦ ╦╔═╗╔═╗ ╦                                     #
#                                    ║║║╚╦╝╚═╗║═╬╗║                                     #
#                                    ╩ ╩ ╩ ╚═╝╚═╝╚╩═╝                                   #
#                                                                                       #
# For the connection to work you just need to create an empty database and configure    #
# the fields that the plugin must take into account and it will take care of the rest!  #
#                                                                                       #
# !! Colors does not work in mysql !!                                                   #
#                                                                                       #
mysql:                                                                                  #
# ------------------------------------------------------------------------------------- #

  # Prefix and suffix MySQL console and chat messages :
  prefix: "&f[&3MySQL&f] "
  suffix: "&f&l->&f "

  # Message success connect/disconnect :
  connectSuccess: "&2Successful connection &c!"
  disconnectSuccess: "&2Successful disconnection &c!"

  # Message failed connect/disconnect :
  connectFail: "&cConnection failed !"
  disconnectFail: "&cDisconnection failed !"

  # Change to true for use DataBase connection :
  use: false

  # Name of the database to connect to, use the name of your database so that you don't have an error.
  # This parameter is the only one that requires you to intervene in your dataBase :
  dbName: "friendsBG"

  # Database tables prefix, leave blank so as not to use it :
  prefixTables: "tm_"

  # Name of servers table, this table store all servers data to on-demand servers system :
  serversTable: "servers"

  # Name of mails table, this table store all mails data :
  mailsTable: "mails"

  # DataBase login, use your DataBase logins for connect this plugin to your DataBase :
  host: "localhost"
  port: 3306
  user: "user"
  password: "password"

  # This is number of pool connexions established by the plugin (Default : 10)
  maxPoolSize: 16 # Default Redis-server config

  # This is max life time of pools in ms :
  maxLifeTime: 600000 # Default = 10 minutes -> 600 000 ms

  # This is time out for pools not used :
  poolTimeout: 300000 # Default = 5 minutes -> 300 000 ms

  # This is time to detect data leak :
  dataLeak: 300000 # Default = 5 minutes -> 300 000 ms

  # This is time out for no pool available :
  timeout: 10000 # Default = 10 seconds -> 10 000 ms


# ##################################################################################### #
#                                     ╦═╗╔═╗╔╦╗╦╔═╗                                     #
#                                     ╠╦╝║╣  ║║║╚═╗                                     #
#                                     ╩╚═╚═╝═╩╝╩╚═╝                                     #
#                                                                                       #
# For use this, you need to install and configure Redis-server on GNU/LINUX or Windows  #
# server. This software is an in-memory database system.                                #
#                                                                                       #
# It can be used as an alternative to MariaDB/MySQL servers.                            #
#                                                                                       #
# !! Colors does not work in redis !!                                                   #
#                                                                                       #
redis:                                                                                  #
# ------------------------------------------------------------------------------------- #

  # Change to true for use redis connection :
  use: false

  # Redisson login, use your Redisson logins for connect this plugin to your Redis server :
  host: "localhost"
  port: 6379
  password: "password"
  clientName: "friendsBG"

  # DataBase connection pool used for get and set information :
  dataBase: 1 # Default = 1

  # This is number of allocated threads to redis server :
  threads: 1 # Default = 1

  # This is number of allocated Netty threads to redis server :
  nettyThreads: 1 # Default = 1


# ##################################################################################### #
#                                 ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗                                 #
#                                 ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗                                 #
#                                 ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝                                 #
#                                                                                       #
updates:                                                                                #
# ##################################################################################### #

  # Turn to true for enable plugin updates checker (Available) :
  checker: true

  # Send message to admins (not available) :
  adminMsg:
    # Turn to true to enable update warning
    use: false
    # Message design
    prefix: "&f[&6UpdateChecker&f] "
    suffix: "&f&l->&f "
    message: "&6New update is available !"


# #################### API made by PataPom - Licensed under GPL3 License. #################### #